name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          docker.pkg.github.com/specialjogger104/docker-image:latest
          docker.pkg.github.com/specialjogger104/docker-image:v1.0.0

    - name: Run Trivy for vulnerability scanning
      run: |
        docker pull aquasec/trivy
        docker run --rm -v $(pwd):/workdir -w /workdir aquasec/trivy --exit-code 0 --severity HIGH docker.pkg.github.com/specialjogger104/docker-image:latest

    - name: Logout from Docker Hub
      uses: docker/logout-action@v1
