name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t docker.pkg.github.com/specialjogger104/docker-image:latest .
        docker push docker.pkg.github.com/specialjogger104/docker-image:latest

    - name: Logout from Docker Hub
      run: docker logout docker.pkg.github.com
