name: Build, Publish, and Scan Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-publish-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u SpecialJogger104 --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t docker.pkg.github.com/specialjogger104/docker-image:latest .
        docker push docker.pkg.github.com/specialjogger104/docker-image:latest

    - name: Scan Docker image for vulnerabilities
      uses: docker/scan-action@v1
      with:
        image-ref: docker.pkg.github.com/specialjogger104/docker-image:latest

    - name: Logout from Docker Hub
      run: docker logout docker.pkg.github.com
