name: Build, scan and Push a Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag specialjogger104/image-docker:v1

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      with:
        image-ref: 'specialjogger104/image-docker:v1'
        format: 'table'
        output: 'trivy-results.sarif'

    - name: Push the Docker image
      run: docker push specialjogger104/image-docker:v1

    - name: Logout from Docker Hub
      run: docker logout docker.pkg.github.com
